### ISSUE TITLE
Unstaged changes lost when pre-commit plugin modified

### ISSUE THREAD

**Issue by seanpclark** [causes/overcommit#129]
During a commit I received the message "The following pre-commit plugins have been added, changed, or..." since a plugin had been modified. At that point (before running overcommit --sign pre-commit), I checked git status and noticed unstaged items were lost.

**Comment by sds** [comment]
Hey @seanpclark,

Are you sure they aren't in your stash? While this is a bug (we should properly restore the stash if the plugin signature validation fails), I believe we always stash changes so that they are never lost.

```
git stash list
```

**Comment by seanpclark** [comment]
@sds You're totally correct... it was stashed and I didn't think to check. Restoring stash would resolve the issue.
