### ISSUE TITLE
Restore old hooks on uninstall

### ISSUE THREAD

**Issue by jawshooah** [causes/overcommit#138]
Currently Overcommit clobbers any existing `pre-commit`, `post-checkout`, etc. hooks it finds already in the `.git/hooks` directory on `overcommit --install`. These hooks should be preserved somewhere and restored on `overcommit --uninstall`.

**Comment by jawshooah** [comment]
Strange, this wasn't working earlier, but now I can't reproduce the clobbering. Probably a good idea to add some tests for this, though.

**Comment by sds** [comment]
If you specify the `--force` flag it will clobber, but that's expected.

**Comment by jawshooah** [comment]
Right, I wasn't though. Must have done something stupid.

Regardless, what do you think about preserving existing hooks rather than just refusing to overwrite them?

**Comment by sds** [comment]
Feel free to submit a pull request. I suppose this is valuable by making it a lower barrier to entry for people to try out overcommit, but I don't think the extra step of backing up your hooks yourself (given it's a simple `cp -R .git/hooks path/to/some/directory/old-hooks`) is that onerous.

**Comment by jawshooah** [comment]
Definitely not onerous, but I think automating it would be useful. Working on a PR now.

**Comment by sds** [comment]
Implemented by #141. Thanks!
