### ISSUE TITLE
Various spec blocks return raw Boolean values rather than using should-matchers

### ISSUE THREAD

**Issue by jawshooah** [causes/overcommit#150]
Throughout the specs, I've noticed a bunch of blocks ending with something like the following:

```ruby
File.open('tracked-file', 'r').read == 'Hello World'
```

This simply returns a Boolean rather than actually performing a test. We know that this doesn't work, because the comparison evaluates to `false` (RHS should be `"Hello World\n"`), but the test still passes. It should be:

```ruby
File.open('tracked-file', 'r').read.should == "Hello World\n"
```

Such invalid tests are peppered throughout the specs. I'm working on a PR now to clean them up.

**Comment by sds** [comment]
Fixed by #151. Thanks!
