### ISSUE TITLE
Add post-merge, post-commit, and post-rebase hooks for indexing tags

### ISSUE THREAD

**Issue by lencioni** [causes/overcommit#72]
The post-checkout index tags hook works well. But, I was recently reading [an article](http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html) where the author set up git hooks to do this for post-merge, post-commit, and post-rebase (via a special case in post-rewrite).

I was thinking that this might be nice to have as well.

**Comment by sds** [comment]
Implemented in 88cd039a72dcc85e04c88f825f799f01635ae1f1.
